version: '3'
services:
  portfolio:
    build:
      context: .
    image: portfolio-angular:v1.0
    ports:
      - "8090:80"
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginx-network